name: "nyc_yellow_taxi"
version: "1.0.0"

profile: "nyc_yellow_taxi"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  nyc_yellow_taxi:
    example:
      +materialized: view
